SectionVerb {
	EnableSequence [
		cset "name='INT0_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='MultiMedia2 Mixer INT3_MI2S_TX' 1"
	]

	DisableSequence [
		cset "name='INT0_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='MultiMedia2 Mixer INT3_MI2S_TX' 0"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Earpiece" {
	Comment "Built-in Earpiece"

	Include.ees.File "/codecs/sdm660-wcd/EarpieceEnableSeq.conf"
	Include.eds.File "/codecs/sdm660-wcd/EarpieceDisableSeq.conf"

	ConflictingDevice [
		"Headphones"
	]

	Value {
		PlaybackPCM "hw:${CardId},0"
		PlaybackPriority 100
	}
}

SectionDevice."Microphone" {
	Comment "Built-in Microphone"

	Include.pmes.File "/codecs/sdm660-wcd/PrimaryMicEnableSeq.conf"
	Include.pmds.File "/codecs/sdm660-wcd/PrimaryMicDisableSeq.conf"

	ConflictingDevice [
		"Headset Mic"
	]

	Value {
		CapturePCM "hw:${CardId},1"
		CapturePriority 100
		CaptureChannels 1
	}
}

SectionDevice."Headphones" {
	Comment "Headphones (3.5 mm jack)"

	Include.hpes.File "/codecs/sdm660-wcd/HeadphonesEnableSeq.conf"
	Include.hpds.File "/codecs/sdm660-wcd/HeadphonesDisableSeq.conf"

	ConflictingDevice [
		"Earpiece"
	]

	Value {
		PlaybackPCM "hw:${CardId},0"
		PlaybackPriority 200
		JackControl "Headset Jack"
	}
}

SectionDevice."Headset Mic" {
	Comment "Headset Microphone"

	Include.hmes.File "/codecs/sdm660-wcd/HeadsetMicEnableSeq.conf"
	Include.hmds.File "/codecs/sdm660-wcd/HeadsetMicDisableSeq.conf"

	ConflictingDevice [
		"Microphone"
	]

	Value {
		CapturePCM "hw:${CardId},1"
		CapturePriority 200
		CaptureChannels 1
		JackControl "Headset Jack"
	}
}
